// console.log(c);
//  c = 30;
//  var c;
//  console.log(c);
//  c = c * 2;
//  console.log(c);
// var d;
//  console.log(d);
//  d = 50;
//  console.log(d);
//  d = d + 10;
//  console.log(d);
//  var d = 100;
//  console.log(d);
var e = 1;
 console.log(e);
 e = e + 1;
 console.log(e);
 var e = 10;
 console.log(e);
 e = e * 2;
 console.log(e);
